### PR TITLE
Make `OnConflict` store both `update_columns` and `values`

### LINKED ISSUE #593: `OnConflict::values` and `OnConflict::update_columns` gets overridden by one another
## Description

Since `OnConflict` uses the builder pattern, it is expected that a call to `values` then `update_columns`, or vice-versa, should create a query with both features, but only the last one gets applied to the query.

## Steps to Reproduce

1. Build an `InsertStatement` with an `OnConflict` clause
2. Add actions using `OnConflict::values([(Column::Col1, false.into())])` and `OnConflict::update_columns([Column::Col2])`
3. Build and check the generated query

### Expected Behavior

PostgreSQL:
   `... DO UPDATE SET "col1" = false, "col2" = "excluded"."col2"`

### Actual Behavior

PostgreSQL:
   `... DO UPDATE SET "col2" = "excluded"."col2"`

Only `OnConflict::update_columns` gets applied since it was used last

### Reproduces How Often

Everytime

## Versions
0.24+ (when `OnConflict` was introduced)

### PR DESCRIPTION
**Pull request by elbertronnie**
## PR Info

- Closes #593 

## Breaking Changes

- [x] `OnConflict::values` and `OnConflict::update_columns` will append the new values keeping the old values intact instead of erasing them

## Changes

- [x] Added new enum `OnConflictUpdate` that determines the column update strategy in ON CONFLICT expressions
- [x] Replaced `UpdateColumns` and `UpdateExprs` with `Update(Vec<OnConflictUpdate>)` in `OnConflictAction`

### CODE REVIEW

File: src/query/on_conflict.rs [hunk 1]
```diff
@@ -20,10 +20,17 @@ pub enum OnConflictTarget {
...
+/// Represents strategies to update column in ON CONFLICT (upsert) actions
+#[derive(Debug, Clone)]
+pub enum UpdateStrat {
     /// Update column value of existing row with inserting value
-    UpdateColumns(Vec<DynIden>),
+    Column(DynIden),
     /// Update column value of existing row with expression
-    UpdateExprs(Vec<(DynIden, SimpleExpr)>),
+    Expr(DynIden, SimpleExpr),
 }
```
Comment (billy1624) [inline src/query/on_conflict.rs:34]: I got a suggested naming for `UpdateStrat`, maybe `OnConflictUpdate`?

**Review by billy1624 — COMMENTED** [review]
Hey @elbertronnie, thanks for contributing!! The implementation looks good to me :)

File: src/query/on_conflict.rs (hunk 1 above)
Comment (elbertronnie) [reply src/query/on_conflict.rs]: I have changed the name to `OnConflictUpdate`

**Review by ikrivosheev — APPROVED** [review]
@elbertronnie thank you! LGTM!

**Review by tyt2y3 — COMMENTED** [review]
It would be nice to also add some doc tests
